const recommendedRules = {
  "effect/no-explicit-any": "error",
  "effect/no-type-casting": "error",
  "effect/no-non-null-assertion": "error",
  "effect/no-ts-nocheck": "error",
  "effect/no-disable-validation": "error",
  "effect/no-raw-throw": "error",
  "effect/no-built-in-error-constructor": "error",
  "effect/no-effect-fail-new-error": "error",
  "effect/no-promise-reject": "error",
  "effect/no-promise-catch": "error",
  "effect/no-effect-ignore": "error",
  "effect/no-silent-error-swallow": "error",
  "effect/no-json-parse": "error",
  "effect/no-schema-error-response-leak": "error",
  "effect/no-unknown-shape-probing": "error",
  "effect/no-unsupported-effect-api": "error",
  "effect/no-unknown-runtime-requirements": "error",
  "effect/no-bare-yield-in-effect-generator": "error",
  "effect/no-floating-effect-in-generator": "error",
  "effect/no-return-effect-from-generator": "error",
  "effect/no-effect-run-in-effect-code": "error",
} as const;

const strictRules = {
  ...recommendedRules,
  "effect/no-sql-type-parameter": "error",
  "effect/no-process-env": "error",
  "effect/prefer-option-from-nullable": "error",
  "effect/no-effect-catchallcause": "error",
  "effect/no-effect-escape-hatch": "error",
  "effect/prefer-map-error-for-wrapping": "error",
  "effect/no-service-option": "error",
  "effect/no-primitive-context-service": "error",
  "effect/no-promise-service-method": "error",
  "effect/no-nested-layer-provide": "error",
  "effect/prefer-layer-provide-merge": "error",
  "effect/no-repeated-layer-factory": "error",
  "effect/prefer-layer-constructor-semantics": "error",
  "effect/prefer-fork-scoped-in-layer": "error",
  "effect/prefer-static-effect": "error",
  "effect/prefer-stream-from-pubsub": "error",
  "effect/prefer-service-log-annotations": "error",
  "effect/no-void-expression": "error",
  "effect/no-direct-fetch": "error",
  "effect/no-native-clock-in-effect": "error",
  "effect/no-native-random-in-effect": "error",
  "effect/no-timer-api-in-effect": "error",
  "effect/no-promise-combinators-in-effect": "error",
  "effect/no-sync-schema-decode-in-effect": "error",
  "effect/no-localstorage": "error",
  "effect/no-raw-indexeddb": "error",
  "effect/no-manual-layer-build-in-tests": "error",
  "effect/no-effect-run-in-tests": "error",
  "effect/no-vitest-import": "error",
  "effect/prefer-effect-vitest": "error",
  "effect/prefer-effect-vitest-assert": "error",
  "effect/prefer-yieldable-error": "error",
  "effect/no-instanceof-error": "error",
  "effect/no-unknown-error-message": "error",
  "effect/prefer-tagged-constructor": "error",
  "effect/prefer-data-tagged-enum": "error",
  "effect/no-manual-tag-check": "error",
  "effect/prefer-schema-tagged-error-class": "error",
  "effect/prefer-effect-fn": "error",
  "effect/no-effect-fn-immediate-invocation": "error",
  "effect/prefer-match-validation": "error",
  "effect/prefer-match-value": "error",
  "effect/prefer-yieldable-error-in-match": "error",
  "effect/no-as-effect-method-reference": "error",
  "effect/prefer-context-service": "error",
  "effect/prefer-inline-context-service-shape": "error",
  "effect/no-inline-schema-compile": "error",
  "effect/no-try-catch": "error",
  "effect/no-unnecessary-effect-tx": "error",
  "effect/prefer-shared-managed-runtime": "error",
  "effect/require-callback-cleanup-for-listeners": "error",
  "effect/prefer-scoped-temp-cleanup": "error",
  "effect/no-nested-semaphore-acquire": "error",
} as const;

export const recommended = {
  jsPlugins: ["effect-rules"],
  rules: recommendedRules,
} as const;

export const strict = {
  jsPlugins: ["effect-rules"],
  rules: strictRules,
} as const;
